spring.application.name=QuizzApplication

spring.datasource.username=root
spring.datasource.password=root

spring.datasource.url=jdbc:mysql://localhost:3306/quizzdb

spring.jpa.hibernate.ddl-auto=update

